#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gitea-runner"
name = "Gitea Runner"
description.en = "Official runner for Gitea Actions"
description.fr = "Runner officiel pour Gitea Actions"
description.pt = "Runner oficial para o Gitea Actions"

# The automated updater replaces this with the newest stable validated release.
version = "2.1.0~ynh3"
maintainers = ["eric_G", "faleious-ai"]

[upstream]
license = "MIT"
website = "https://docs.gitea.com/usage/actions/runner"
admindoc = "https://docs.gitea.com/usage/actions/runner"
code = "https://gitea.com/gitea/runner"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false
